# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(211E1E)
$foreground = rgb(FAE1C1)
$color0 = rgb(484444)
$color1 = rgb(291B17)
$color2 = rgb(62291E)
$color3 = rgb(573C23)
$color4 = rgb(963A26)
$color5 = rgb(865D2E)
$color6 = rgb(B47F3A)
$color7 = rgb(EFCC9E)
$color8 = rgb(A78E6E)
$color9 = rgb(36241F)
$color10 = rgb(833728)
$color11 = rgb(74502E)
$color12 = rgb(C84D32)
$color13 = rgb(B27D3E)
$color14 = rgb(F0A94D)
$color15 = rgb(EFCC9E)
