layout splits

# 1. Abre o relógio na tela principal
launch tty-clock -c -B -C 7

# 2. Divide a tela na vertical (metade direita) e abre o Fastfetch
launch --location=vsplit sh -c "fastfetch; exec fish"

# 3. Divide essa nova metade na horizontal (embaixo) e abre o btop
launch --location=hsplit btop
