# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #FAE1C1
background         #211E1E
cursor             #BE8C75

active_tab_foreground     #211E1E
active_tab_background     #FAE1C1
inactive_tab_foreground   #FAE1C1
inactive_tab_background   #211E1E

active_border_color   #FAE1C1
inactive_border_color #211E1E
bell_border_color     #291B17

color0      #484444
color1		#291B17
color2		#62291E
color3		#573C23
color4		#963A26
color5		#865D2E
color6		#B47F3A
color7		#EFCC9E
color8		#A78E6E
color9		#36241F
color10		#833728
color11		#74502E
color12		#C84D32
color13		#B27D3E
color14		#F0A94D
color15		#EFCC9E
