# ===============================
# Cursor
# ===============================
exec-once = hyprctl setcursor Changli 40

# ===============================
# Quickshell
# ===============================
exec-once = quickshell

# ===============================
# GLava (exemplo)
# ===============================
# exec-once = glava

# ===============================
# Seus scripts
# ===============================
# exec-once = ~/.config/scripts/inicia.sh
