# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules 
# This file will not be modified during dotfiles updates

# Regras para travar o layout na Workspace 1
windowrulev2 = workspace 1, class:^(kitty-clock)$
windowrulev2 = workspace 1, class:^(kitty-fetch)$
windowrulev2 = workspace 1, class:^(kitty-btop)$