monitor = DP-1, 3440x1440@165, auto, 1
hl.bind("SUPER + ALT + Up", hl.dsp.exec_cmd("pkill rofi || rofi -show drun -theme /home/Pedro/.config/rofi/dashboard.rasi"))

monitor = HDMI-A-2, modeline 173.00 1920 2048 2248 2576 1080 1083 1088 1120 -hsync +vsync, 3440x0, 1
