# Regras para o GLava ficar fixo no fundo
windowrulev2 = float, class:^(GLava)$
windowrulev2 = pin, class:^(GLava)$
windowrulev2 = nofocus, class:^(GLava)$
windowrulev2 = noinitialfocus, class:^(GLava)$
windowrulev2 = noanim, class:^(GLava)$
windowrulev2 = noborder, class:^(GLava)$
windowrulev2 = noshadow, class:^(GLava)$